### ISSUE TITLE
Finalize design for "Header image with CTA and CTAs in a row" layout

### ISSUE THREAD

**Issue by hannahkane** [mozilla/mozmaker-templates#6]
We've started this layout, but during the March 11 heartbeat, we need to finalize. This should include:
- [ ] design for specific use case (Letters to the Next President campaign) (p1)
- [ ] generic design (p2)
- [ ] design review and necessary revisions

**Comment by hannahkane** [comment]
As discussed at kickoff meeting, this ticket is the one we'll cut from the milestone if needed.

**Comment by flukeout** [comment]
@hannahkane @chadsansing Do you have some more info about the Letters to the Next President use-case?

**Comment by hannahkane** [comment]
@flukeout - check out this ticket: https://github.com/mozilla/teach.mozilla.org/issues/1682

**Comment by flukeout** [comment]
Oh, duh - thanks!

**Comment by flukeout** [comment]
Here's a first pass based based on the Letters to the Next President campaign. It has some shared elements with the 3 column with images template that @vazquez is working on right now, so I've left it fairly wireframe-y. We'll see how that shakes out and carry the styles over.

![header-image-with-cta](https://cloud.githubusercontent.com/assets/25212/13610117/09ad4666-e511-11e5-918d-668dfc93bc14.png)

**Comment by hannahkane** [comment]
@flukeout - I think you should do all of our copywriting. :)

This looks good. Is the gallery ("nice to have") an opportunity for us to explore a new component for layouts? Or is that overcomplicating things at this stage?

**Comment by flukeout** [comment]
@hannahkane Haha, thanks. Yeah, the gallery would be a nice way to dig into this stuff, especially if we're going to put some effort into fixing the dashboard. We could potentially include an iframe to the dashboard with a specific search string to accomplish this. 

I'll add a potential design to this ticket.

**Comment by flukeout** [comment]
Here's a wireframe for a **Thimble Gallery** component as it might appear in this page...

![image](https://cloud.githubusercontent.com/assets/25212/13617305/f301ac50-e532-11e5-9981-8fabbddf4a86.png)

**How it might work**
This could be in iframe to a special gallery page on the Thimble dashboard service that we'll be resurrecting soon. We could make it so that URL of the iframe sets the parameters for the gallery view...
- How many Rows to show (we could hardcode this to a 3 x 2 grid though)
- What search terms / parameters to use
  - Ex. keywords in the description or title of the project
- How to sort the projects
  - Ex. Show newest first, or show most popular or remixed first?

This will be a little tricky on the TinyMCE front. If we stick with an approach similar to the solution for the Etherpad in http://flukeout.github.io/master-template/template-types/editor-etherpad.html - that leaves us with just one editable text area to pass on the info that the gallery needs. A couple of options...
- We ask people to pass on the querystring only, and then append it to the src tag for the iframe
  - ``?search=president&results=20&sort-by=date
- We have a tool or page on the gallery that lets you build a gallery with a unique URL, then you paste that into TinyMCE
  - ``http://thimble-gallery.org/president
- You just paste the entire URL for the iframe after you've built & configured the gallery separately

cc @vazquez

**Comment by hannahkane** [comment]
Is it important to think about other possible dynamically-generated Galleries, in addition to a Thimble-specific one at this point, or does that unnecessarily complicate the issue? A variation with a lot of potential use cases would be a gallery based on pages created in the CMS within a certain category (or tag?) (e.g. Club Pages).

If that's a distraction at this point, feel free to disregard.

**Comment by flukeout** [comment]
I think each gallery type (Thimble, Collection of CMS Pages, Flickr) would probably have to be a custom component. It probably makes sense to think about which of the ones we're thinking about here in this issue would be used the most and provide most bang 4 buck.

**Comment by hannahkane** [comment]
I think all three of those are likely to be used regularly. 

The Thimble Gallery would be used for partner campaigns (where we often create custom Thimble projects - here's another example: https://teach.mozilla.org/activities/madewithcode/), as well as to supplement learning content. (I can also imagine a use case for Educators who want to create a gallery of their students' work—but that raises an issue about granular permissions.)

The Gallery of CMS pages would be used for a directory of Club pages, as I mentioned above, but also any kind of "portfolio"—Hives have Portfolios, for example. (See http://hivecha.org/portfolio/ as an example).

And a Flickr gallery would often be used to promote/tell the story of our own campaigns and events (e.g. Maker Party, Hive Buzz, MozFest).

I can file separate tickets for each of these, and we can prioritize accordingly. Not suggesting we solve them all in this ticket.

**Comment by flukeout** [comment]
Sounds good - let's file separately and prioritize.

**Comment by hannahkane** [comment]
K. Will do.
